export const languageOptions = [
  { code: "EN", label: "EN", htmlLang: "en", dir: "ltr" },
  { code: "JA", label: "JA", htmlLang: "ja", dir: "ltr" },
  { code: "ZH", label: "ZH", htmlLang: "zh-CN", dir: "ltr" },
  { code: "KO", label: "KO", htmlLang: "ko", dir: "ltr" },
  { code: "DE", label: "DE", htmlLang: "de", dir: "ltr" },
  { code: "FR", label: "FR", htmlLang: "fr", dir: "ltr" },
  { code: "AR", label: "AR", htmlLang: "ar", dir: "rtl" }
] as const;

export type LanguageCode = (typeof languageOptions)[number]["code"];

type MarketplaceCopy = {
  addGoogle: string;
  admin: string;
  area: string;
  availableEyebrow: string;
  brandSub: string;
  calendarDemo: string;
  calendarPersonalFallback: string;
  calendarServerCreated: string;
  calendarServerPending: string;
  categories: Record<string, string>;
  categoriesAria: string;
  chooseSlot: string;
  confirmationTitle: string;
  confirmed: string;
  customerError: string;
  date: string;
  demoConfirmed: string;
  downloadIcs: string;
  email: string;
  estimatedTotal: string;
  galleryAria: string;
  galleryLabels: string[];
  guestUnit: string;
  guests: string;
  heroEyebrow: string;
  heroText: string;
  heroTitle: string;
  host: string;
  hostPending: string;
  keyword: string;
  keywordPlaceholder: string;
  loading: string;
  minuteSuffix: string;
  name: string;
  perGuest: string;
  phone: string;
  regions: Record<string, string>;
  request: string;
  requestPlaceholder: string;
  reservationError: string;
  reserveButton: string;
  reserveEyebrow: string;
  reviews: string;
  reviewsNav: string;
  reviewEyebrow: string;
  reviewQuotes: string[];
  reviewTitle: string;
  routesMatch: string;
  searchAria: string;
  selectTour: string;
  tours: string;
  trust: string[];
  unavailable: string;
  viewSlots: string;
};

export const marketplaceCopy: Record<LanguageCode, MarketplaceCopy> = {
  EN: {
    addGoogle: "Add to Google Calendar",
    admin: "Admin",
    area: "Area",
    availableEyebrow: "Available experiences",
    brandSub: "JDM night access",
    calendarDemo: "Demo mode: use the calendar buttons below to add this schedule.",
    calendarPersonalFallback: "Reservation saved. Add it to a personal calendar with the buttons below.",
    calendarServerCreated: "Google Calendar event was created for the operation calendar.",
    calendarServerPending: "Google Calendar sync will run after the reservation is saved.",
    categories: { All: "All", Signature: "Signature", VIP: "VIP", Culture: "Culture", Tours: "Tours" },
    categoriesAria: "Categories",
    chooseSlot: "Choose an available slot before reserving.",
    confirmationTitle: "Reservation confirmed",
    confirmed: "Reservation confirmed.",
    customerError: "Customer could not be created.",
    date: "Date",
    demoConfirmed: "Reservation confirmed in demo mode. Calendar options are ready.",
    downloadIcs: "Download ICS",
    email: "Email",
    estimatedTotal: "Estimated total",
    galleryAria: "Car gallery",
    galleryLabels: ["Supercar night line", "Imported coupe", "Muscle silhouette", "European performance", "Track-spec detail", "Tokyo tunnel run"],
    guestUnit: "guests",
    guests: "Guests",
    heroEyebrow: "Tokyo after the last train",
    heroText: "Search private routes, compare hosts, check live availability, and reserve a cinematic Tokyo car culture experience in minutes.",
    heroTitle: "Reserve real JDM nights, not tourist theater.",
    host: "Host",
    hostPending: "Host pending",
    keyword: "Keyword",
    keywordPlaceholder: "C1, Daikoku, garage, VIP",
    loading: "Loading Midnight Tokyo Club...",
    minuteSuffix: "min",
    name: "Name",
    perGuest: "/ guest",
    phone: "Phone",
    regions: { "All Tokyo": "All Tokyo", Shibuya: "Shibuya", Yokohama: "Yokohama", "C1 Route": "C1 Route", Daikoku: "Daikoku" },
    request: "Request",
    requestPlaceholder: "Car preference, pickup, filming",
    reservationError: "Reservation could not be created.",
    reserveButton: "Reserve This Slot",
    reserveEyebrow: "Reserve online",
    reviews: "reviews",
    reviewsNav: "Reviews",
    reviewEyebrow: "Guest signal",
    reviewQuotes: ["Not a staged tour. It felt like being invited into the scene for one night.", "The host knew every car, every route, and when to move. Worth the late night.", "Private, precise, and cinematic. The garage access was the part I keep talking about."],
    reviewTitle: "Built for travelers who already know why C1 matters.",
    routesMatch: "{count} routes match your night.",
    searchAria: "Tour search",
    selectTour: "Select a tour",
    tours: "Tours",
    trust: ["4.9 average rating", "English-first concierge", "Stripe-ready checkout", "Google Calendar-ready"],
    unavailable: "That slot is no longer available.",
    viewSlots: "View Slots"
  },
  JA: {
    addGoogle: "Googleカレンダーに追加",
    admin: "管理",
    area: "エリア",
    availableEyebrow: "予約可能な体験",
    brandSub: "JDMナイトアクセス",
    calendarDemo: "デモモードです。下のボタンでスケジュールを追加できます。",
    calendarPersonalFallback: "予約は保存されました。下のボタンから個人カレンダーへ追加できます。",
    calendarServerCreated: "運営用Googleカレンダーに予定を作成しました。",
    calendarServerPending: "予約保存後にGoogleカレンダー同期を実行します。",
    categories: { All: "すべて", Signature: "シグネチャー", VIP: "VIP", Culture: "カルチャー", Tours: "ツアー" },
    categoriesAria: "カテゴリ",
    chooseSlot: "予約前に空き枠を選択してください。",
    confirmationTitle: "予約が確定しました",
    confirmed: "予約が確定しました。",
    customerError: "顧客情報を作成できませんでした。",
    date: "日付",
    demoConfirmed: "デモ予約が確定しました。カレンダー追加が使えます。",
    downloadIcs: "ICSをダウンロード",
    email: "メール",
    estimatedTotal: "概算合計",
    galleryAria: "車両ギャラリー",
    galleryLabels: ["スーパーカーの夜", "輸入クーペ", "マッスルシルエット", "欧州パフォーマンス", "トラック仕様ディテール", "東京トンネルラン"],
    guestUnit: "名",
    guests: "人数",
    heroEyebrow: "終電後の東京",
    heroText: "プライベートルートを検索し、ホストを比較し、空き枠を確認して、映画のような東京の車文化体験を数分で予約できます。",
    heroTitle: "観光ではない、本物のJDMナイトを予約。",
    host: "ホスト",
    hostPending: "ホスト未選択",
    keyword: "キーワード",
    keywordPlaceholder: "C1、Daikoku、garage、VIP",
    loading: "Midnight Tokyo Clubを読み込み中...",
    minuteSuffix: "分",
    name: "名前",
    perGuest: "/ 名",
    phone: "電話番号",
    regions: { "All Tokyo": "東京全域", Shibuya: "渋谷", Yokohama: "横浜", "C1 Route": "C1ルート", Daikoku: "大黒" },
    request: "リクエスト",
    requestPlaceholder: "車種希望、送迎、撮影など",
    reservationError: "予約を作成できませんでした。",
    reserveButton: "この枠を予約",
    reserveEyebrow: "オンライン予約",
    reviews: "件のレビュー",
    reviewsNav: "レビュー",
    reviewEyebrow: "ゲストの声",
    reviewQuotes: ["演出されたツアーではなく、一夜だけ本物のシーンに招かれた感覚でした。", "ホストは車もルートも動くタイミングもすべて分かっていた。夜更かしする価値があります。", "プライベートで精密、そしてシネマティック。ガレージアクセスが今も話題です。"],
    reviewTitle: "C1の意味を知っている旅人のために作られています。",
    routesMatch: "{count}件のルートが見つかりました。",
    searchAria: "ツアー検索",
    selectTour: "ツアーを選択",
    tours: "ツアー",
    trust: ["平均評価4.9", "英語対応コンシェルジュ", "Stripe決済対応", "Googleカレンダー対応"],
    unavailable: "その枠は現在利用できません。",
    viewSlots: "空き枠を見る"
  },
  ZH: {
    addGoogle: "添加到Google日历",
    admin: "管理",
    area: "地区",
    availableEyebrow: "可预约体验",
    brandSub: "JDM夜间体验",
    calendarDemo: "演示模式：可使用下方按钮添加日程。",
    calendarPersonalFallback: "预约已保存。可用下方按钮添加到个人日历。",
    calendarServerCreated: "已在运营Google日历中创建事件。",
    calendarServerPending: "预约保存后将同步Google日历。",
    categories: { All: "全部", Signature: "招牌", VIP: "VIP", Culture: "文化", Tours: "行程" },
    categoriesAria: "分类",
    chooseSlot: "预约前请选择可用时段。",
    confirmationTitle: "预约已确认",
    confirmed: "预约已确认。",
    customerError: "无法创建客户信息。",
    date: "日期",
    demoConfirmed: "演示预约已确认。日历选项已准备好。",
    downloadIcs: "下载ICS",
    email: "邮箱",
    estimatedTotal: "预计合计",
    galleryAria: "车辆图库",
    galleryLabels: ["超跑夜线", "进口双门车", "肌肉车剪影", "欧洲性能车", "赛道规格细节", "东京隧道夜跑"],
    guestUnit: "人",
    guests: "人数",
    heroEyebrow: "末班车后的东京",
    heroText: "搜索私人路线，比较向导，查看实时空位，并在几分钟内预约电影感的东京车文化体验。",
    heroTitle: "预约真正的JDM夜晚，而不是游客表演。",
    host: "向导",
    hostPending: "待选向导",
    keyword: "关键词",
    keywordPlaceholder: "C1, Daikoku, garage, VIP",
    loading: "正在加载Midnight Tokyo Club...",
    minuteSuffix: "分钟",
    name: "姓名",
    perGuest: "/ 人",
    phone: "电话",
    regions: { "All Tokyo": "东京全部", Shibuya: "涩谷", Yokohama: "横滨", "C1 Route": "C1路线", Daikoku: "大黑" },
    request: "需求",
    requestPlaceholder: "车型偏好、接送、拍摄等",
    reservationError: "无法创建预约。",
    reserveButton: "预约此时段",
    reserveEyebrow: "在线预约",
    reviews: "条评价",
    reviewsNav: "评价",
    reviewEyebrow: "客人反馈",
    reviewQuotes: ["这不是摆拍行程，而像被邀请进入真实圈子的一晚。", "向导了解每一台车、每一条路线和移动时机。值得熬夜。", "私密、精准、电影感。车库访问是我一直在讲的部分。"],
    reviewTitle: "为已经理解C1意义的旅行者而设计。",
    routesMatch: "找到{count}条适合今晚的路线。",
    searchAria: "行程搜索",
    selectTour: "选择行程",
    tours: "行程",
    trust: ["平均评分4.9", "英文优先礼宾", "支持Stripe支付", "支持Google日历"],
    unavailable: "该时段已不可用。",
    viewSlots: "查看空位"
  },
  KO: {
    addGoogle: "Google 캘린더에 추가",
    admin: "관리",
    area: "지역",
    availableEyebrow: "예약 가능한 체험",
    brandSub: "JDM 나이트 액세스",
    calendarDemo: "데모 모드: 아래 버튼으로 일정을 추가하세요.",
    calendarPersonalFallback: "예약이 저장되었습니다. 아래 버튼으로 개인 캘린더에 추가하세요.",
    calendarServerCreated: "운영 Google 캘린더에 일정이 생성되었습니다.",
    calendarServerPending: "예약 저장 후 Google 캘린더 동기화가 실행됩니다.",
    categories: { All: "전체", Signature: "시그니처", VIP: "VIP", Culture: "컬처", Tours: "투어" },
    categoriesAria: "카테고리",
    chooseSlot: "예약 전에 가능한 시간을 선택하세요.",
    confirmationTitle: "예약 확정",
    confirmed: "예약이 확정되었습니다.",
    customerError: "고객 정보를 만들 수 없습니다.",
    date: "날짜",
    demoConfirmed: "데모 예약이 확정되었습니다. 캘린더 옵션이 준비되었습니다.",
    downloadIcs: "ICS 다운로드",
    email: "이메일",
    estimatedTotal: "예상 합계",
    galleryAria: "차량 갤러리",
    galleryLabels: ["슈퍼카 나이트 라인", "수입 쿠페", "머슬 실루엣", "유럽 퍼포먼스", "트랙 사양 디테일", "도쿄 터널 런"],
    guestUnit: "명",
    guests: "인원",
    heroEyebrow: "막차 이후의 도쿄",
    heroText: "프라이빗 루트를 검색하고 호스트를 비교하며 실시간 빈 시간을 확인해 도쿄 자동차 문화를 몇 분 안에 예약하세요.",
    heroTitle: "관광이 아닌 진짜 JDM 나이트를 예약하세요.",
    host: "호스트",
    hostPending: "호스트 미선택",
    keyword: "키워드",
    keywordPlaceholder: "C1, Daikoku, garage, VIP",
    loading: "Midnight Tokyo Club 로딩 중...",
    minuteSuffix: "분",
    name: "이름",
    perGuest: "/ 인",
    phone: "전화",
    regions: { "All Tokyo": "도쿄 전체", Shibuya: "시부야", Yokohama: "요코하마", "C1 Route": "C1 루트", Daikoku: "다이코쿠" },
    request: "요청",
    requestPlaceholder: "차량 선호, 픽업, 촬영 등",
    reservationError: "예약을 만들 수 없습니다.",
    reserveButton: "이 시간 예약",
    reserveEyebrow: "온라인 예약",
    reviews: "리뷰",
    reviewsNav: "리뷰",
    reviewEyebrow: "게스트 시그널",
    reviewQuotes: ["연출된 투어가 아니라 하룻밤 진짜 씬에 초대받은 느낌이었습니다.", "호스트는 모든 차와 루트, 움직일 타이밍을 알고 있었습니다. 늦은 밤의 가치가 있습니다.", "프라이빗하고 정교하며 영화 같았습니다. 차고 접근이 가장 기억납니다."],
    reviewTitle: "C1의 의미를 이미 아는 여행자를 위해 만들었습니다.",
    routesMatch: "{count}개의 루트가 맞습니다.",
    searchAria: "투어 검색",
    selectTour: "투어 선택",
    tours: "투어",
    trust: ["평균 평점 4.9", "영어 우선 컨시어지", "Stripe 결제 지원", "Google 캘린더 지원"],
    unavailable: "해당 시간은 더 이상 사용할 수 없습니다.",
    viewSlots: "빈 시간 보기"
  },
  DE: {
    addGoogle: "Zu Google Calendar",
    admin: "Admin",
    area: "Gebiet",
    availableEyebrow: "Verfügbare Erlebnisse",
    brandSub: "JDM-Nachtzugang",
    calendarDemo: "Demo-Modus: Nutze die Buttons unten, um den Termin hinzuzufügen.",
    calendarPersonalFallback: "Reservierung gespeichert. Unten kannst du sie deinem Kalender hinzufügen.",
    calendarServerCreated: "Google-Calendar-Termin wurde im Betriebskalender erstellt.",
    calendarServerPending: "Google Calendar wird nach dem Speichern synchronisiert.",
    categories: { All: "Alle", Signature: "Signature", VIP: "VIP", Culture: "Kultur", Tours: "Touren" },
    categoriesAria: "Kategorien",
    chooseSlot: "Bitte wähle vor der Reservierung eine verfügbare Zeit.",
    confirmationTitle: "Reservierung bestätigt",
    confirmed: "Reservierung bestätigt.",
    customerError: "Kundendaten konnten nicht erstellt werden.",
    date: "Datum",
    demoConfirmed: "Demo-Reservierung bestätigt. Kalenderoptionen sind bereit.",
    downloadIcs: "ICS herunterladen",
    email: "E-Mail",
    estimatedTotal: "Geschätztsumme",
    galleryAria: "Fahrzeuggalerie",
    galleryLabels: ["Supercar Night Line", "Import-Coupé", "Muscle-Silhouette", "Europäische Performance", "Track-Detail", "Tokyo Tunnel Run"],
    guestUnit: "Gäste",
    guests: "Gäste",
    heroEyebrow: "Tokio nach dem letzten Zug",
    heroText: "Suche private Routen, vergleiche Hosts, prüfe Live-Verfügbarkeit und reserviere ein filmisches Tokyo-Car-Culture-Erlebnis in Minuten.",
    heroTitle: "Buche echte JDM-Nächte, kein Touristenschauspiel.",
    host: "Host",
    hostPending: "Host offen",
    keyword: "Keyword",
    keywordPlaceholder: "C1, Daikoku, Garage, VIP",
    loading: "Midnight Tokyo Club wird geladen...",
    minuteSuffix: "Min.",
    name: "Name",
    perGuest: "/ Gast",
    phone: "Telefon",
    regions: { "All Tokyo": "Ganz Tokio", Shibuya: "Shibuya", Yokohama: "Yokohama", "C1 Route": "C1-Route", Daikoku: "Daikoku" },
    request: "Wunsch",
    requestPlaceholder: "Auto, Abholung, Filmwunsch",
    reservationError: "Reservierung konnte nicht erstellt werden.",
    reserveButton: "Zeit reservieren",
    reserveEyebrow: "Online reservieren",
    reviews: "Bewertungen",
    reviewsNav: "Bewertungen",
    reviewEyebrow: "Gäste-Signal",
    reviewQuotes: ["Keine inszenierte Tour. Es fühlte sich an, als wäre man für eine Nacht in die Szene eingeladen.", "Der Host kannte jedes Auto, jede Route und den richtigen Moment. Die Nacht war es wert.", "Privat, präzise und filmisch. Der Garage-Zugang bleibt das Gesprächsthema."],
    reviewTitle: "Gebaut für Reisende, die wissen, warum C1 zählt.",
    routesMatch: "{count} Routen passen zu deiner Nacht.",
    searchAria: "Tourensuche",
    selectTour: "Tour wählen",
    tours: "Touren",
    trust: ["4,9 Durchschnitt", "Concierge zuerst auf Englisch", "Stripe bereit", "Google Calendar bereit"],
    unavailable: "Diese Zeit ist nicht mehr verfügbar.",
    viewSlots: "Zeiten ansehen"
  },
  FR: {
    addGoogle: "Ajouter à Google Calendar",
    admin: "Admin",
    area: "Zone",
    availableEyebrow: "Expériences disponibles",
    brandSub: "Accès nuit JDM",
    calendarDemo: "Mode démo : utilisez les boutons ci-dessous pour ajouter ce planning.",
    calendarPersonalFallback: "Réservation enregistrée. Ajoutez-la à votre calendrier ci-dessous.",
    calendarServerCreated: "L'événement a été créé dans Google Calendar.",
    calendarServerPending: "La synchronisation Google Calendar sera lancée après l'enregistrement.",
    categories: { All: "Tous", Signature: "Signature", VIP: "VIP", Culture: "Culture", Tours: "Tours" },
    categoriesAria: "Catégories",
    chooseSlot: "Choisissez un créneau disponible avant de réserver.",
    confirmationTitle: "Réservation confirmée",
    confirmed: "Réservation confirmée.",
    customerError: "Impossible de créer le client.",
    date: "Date",
    demoConfirmed: "Réservation démo confirmée. Les options calendrier sont prêtes.",
    downloadIcs: "Télécharger ICS",
    email: "E-mail",
    estimatedTotal: "Total estimé",
    galleryAria: "Galerie de voitures",
    galleryLabels: ["Ligne nocturne supercar", "Coupé importé", "Silhouette muscle", "Performance européenne", "Détail piste", "Tunnel run Tokyo"],
    guestUnit: "invités",
    guests: "Invités",
    heroEyebrow: "Tokyo après le dernier train",
    heroText: "Cherchez des routes privées, comparez les hôtes, vérifiez les disponibilités et réservez une expérience automobile cinématique à Tokyo.",
    heroTitle: "Réservez de vraies nuits JDM, pas un spectacle touristique.",
    host: "Hôte",
    hostPending: "Hôte à choisir",
    keyword: "Mot-clé",
    keywordPlaceholder: "C1, Daikoku, garage, VIP",
    loading: "Chargement de Midnight Tokyo Club...",
    minuteSuffix: "min",
    name: "Nom",
    perGuest: "/ invité",
    phone: "Téléphone",
    regions: { "All Tokyo": "Tout Tokyo", Shibuya: "Shibuya", Yokohama: "Yokohama", "C1 Route": "Route C1", Daikoku: "Daikoku" },
    request: "Demande",
    requestPlaceholder: "Voiture, prise en charge, tournage",
    reservationError: "Impossible de créer la réservation.",
    reserveButton: "Réserver ce créneau",
    reserveEyebrow: "Réserver en ligne",
    reviews: "avis",
    reviewsNav: "Avis",
    reviewEyebrow: "Signal client",
    reviewQuotes: ["Pas une visite mise en scène. On avait l'impression d'être invité dans la scène pour une nuit.", "L'hôte connaissait chaque voiture, chaque route et le bon moment pour bouger. La nuit valait le coup.", "Privé, précis et cinématique. L'accès au garage reste ce dont je parle encore."],
    reviewTitle: "Pensé pour les voyageurs qui savent déjà pourquoi C1 compte.",
    routesMatch: "{count} routes correspondent à votre nuit.",
    searchAria: "Recherche de tours",
    selectTour: "Choisir un tour",
    tours: "Tours",
    trust: ["Note moyenne 4,9", "Conciergerie en anglais", "Paiement Stripe prêt", "Google Calendar prêt"],
    unavailable: "Ce créneau n'est plus disponible.",
    viewSlots: "Voir les créneaux"
  },
  AR: {
    addGoogle: "إضافة إلى Google Calendar",
    admin: "الإدارة",
    area: "المنطقة",
    availableEyebrow: "تجارب متاحة",
    brandSub: "وصول ليلي إلى JDM",
    calendarDemo: "وضع تجريبي: استخدم الأزرار أدناه لإضافة الجدول.",
    calendarPersonalFallback: "تم حفظ الحجز. أضفه إلى تقويمك الشخصي من الأزرار أدناه.",
    calendarServerCreated: "تم إنشاء الحدث في تقويم التشغيل على Google.",
    calendarServerPending: "سيتم تشغيل مزامنة Google Calendar بعد حفظ الحجز.",
    categories: { All: "الكل", Signature: "مميز", VIP: "VIP", Culture: "ثقافة", Tours: "جولات" },
    categoriesAria: "الفئات",
    chooseSlot: "اختر موعدا متاحا قبل الحجز.",
    confirmationTitle: "تم تأكيد الحجز",
    confirmed: "تم تأكيد الحجز.",
    customerError: "تعذر إنشاء بيانات العميل.",
    date: "التاريخ",
    demoConfirmed: "تم تأكيد الحجز التجريبي. خيارات التقويم جاهزة.",
    downloadIcs: "تحميل ICS",
    email: "البريد",
    estimatedTotal: "الإجمالي التقديري",
    galleryAria: "معرض السيارات",
    galleryLabels: ["خط سوبركار ليلي", "كوبيه مستوردة", "ظل سيارة عضلية", "أداء أوروبي", "تفاصيل حلبة", "نفق طوكيو الليلي"],
    guestUnit: "ضيوف",
    guests: "الضيوف",
    heroEyebrow: "طوكيو بعد آخر قطار",
    heroText: "ابحث عن مسارات خاصة، قارن المضيفين، تحقق من التوفر المباشر، واحجز تجربة سيارات سينمائية في طوكيو خلال دقائق.",
    heroTitle: "احجز ليالي JDM حقيقية، لا عرضا سياحيا.",
    host: "المضيف",
    hostPending: "المضيف غير محدد",
    keyword: "كلمة البحث",
    keywordPlaceholder: "C1, Daikoku, garage, VIP",
    loading: "جار تحميل Midnight Tokyo Club...",
    minuteSuffix: "دقيقة",
    name: "الاسم",
    perGuest: "/ ضيف",
    phone: "الهاتف",
    regions: { "All Tokyo": "كل طوكيو", Shibuya: "شيبويا", Yokohama: "يوكوهاما", "C1 Route": "مسار C1", Daikoku: "دايكوكو" },
    request: "الطلب",
    requestPlaceholder: "تفضيل السيارة، التوصيل، التصوير",
    reservationError: "تعذر إنشاء الحجز.",
    reserveButton: "احجز هذا الموعد",
    reserveEyebrow: "احجز عبر الإنترنت",
    reviews: "تقييم",
    reviewsNav: "التقييمات",
    reviewEyebrow: "آراء الضيوف",
    reviewQuotes: ["ليست جولة مصطنعة. شعرت كأنني مدعو إلى المشهد الحقيقي لليلة واحدة.", "كان المضيف يعرف كل سيارة وكل مسار ومتى نتحرك. السهر كان يستحق.", "خاص ودقيق وسينمائي. دخول المرآب هو أكثر ما أتحدث عنه."],
    reviewTitle: "مصمم للمسافرين الذين يعرفون لماذا يهم C1.",
    routesMatch: "{count} مسارات تناسب ليلتك.",
    searchAria: "بحث الجولات",
    selectTour: "اختر جولة",
    tours: "الجولات",
    trust: ["تقييم متوسط 4.9", "كونسيرج باللغة الإنجليزية", "دفع Stripe جاهز", "Google Calendar جاهز"],
    unavailable: "هذا الموعد لم يعد متاحا.",
    viewSlots: "عرض الأوقات"
  }
};
